### ISSUE TITLE
hotfix gitflow

### ISSUE THREAD

**Issue by maxfriedmann** [SunGard-Labs/grunt-sg-release#6]
Hi there,
luckily I found this package before adding all of what this does to grunt-bump!

I have a question though... How can I perform a hotfix release with this package? Meaning, instead of starting with branching of develop, rather branch of master, pause in the middle, do my hotfix changes on this hotfix branch and then merge to back to master + merge to develop?

**Comment by passelin** [comment]
At the moment, there's no clean way. However, we're pretty close since the normal release branch flow is essentially the same as the hotfix flow except for the starting branch.

If you look at the code, the sg-release task performs the following tasks: 

1. prepare_sg_release - creates a {tempReleaseBranch}/v#.#.# branch
2. bump - normal bump
3. merge_sg_release - merges back to master and develop, deletes {tempReleaseBranch}/v#.#.#
4. bump-only - bumps versions on develop branch
5. finish_sg_release - push develop and master + tag

So if we were to add a hotfixBranch option and a --hotfix flag to specify the type of release we want, we'd get a clean way to do this.

As for the pause, we'd need to allow running prepare_sg_release separately from the rest (ala bump-only) to split the process in two.

You are welcome to give it a try and submit a pull request :)

**Comment by maxfriedmann** [comment]
Ok, I'll give it a try :)

**Comment by maxfriedmann** [comment]
Hi again,
am pretty close to finishing that thing. Unfortunately, it seems that I cannot use nested grunt.initConfig options within your plugin. My Idea was to introduce two new parameters (startOnly, finishOnly, similar to the jgit flow from atlassian) to change as less as possible in your plugin. This is how my config now looks like : 

```
 sg_release: {
            options: {
                developBranch: 'develop',
                masterBranch: 'master',
                files: [
                    'package.json',
                    'bower.json'
                ],
                commitMessage: 'Release v%VERSION%',
                commitFiles: ['-a'],
                pushTo: 'origin',
                push: false,
                tagName: '%VERSION%',
                createTag: true
            },
            hotfixStart: {
                options: {
                    commitMessage: 'Hotfix v%VERSION%',
                    tempReleaseBranch: 'hotfix',
                    push: true,
                    startOnly: true
                }
            },
            hotfixFinish: {
                options: {
                    commitMessage: 'Hotfix v%VERSION%',
                    tempReleaseBranch: 'hotfix',
                    push: false,
                    finishOnly: true
                }
            }
        }
```

So I can call "grunt sg_release:hotfixStart", do my changes and finish with "grunt sg_release:hotfixFinish". Unfortunately even e.g. "commitMessage" is not overwritten. 

Any clue why?

**Comment by ruyadorno** [comment]
Sorry if it's not really pertinent - it have been some time since I last played with Grunt.

Just to be sure, can you try setting up the config like this instead:

```js
 sg_release: {
            options: {
                developBranch: 'develop',
                masterBranch: 'master',
                files: [
                    'package.json',
                    'bower.json'
                ],
                commitMessage: 'Release v%VERSION%',
                commitFiles: ['-a'],
                pushTo: 'origin',
                push: false,
                tagName: '%VERSION%',
                createTag: true
            },
            hotfixStart: {
                commitMessage: 'Hotfix v%VERSION%',
                tempReleaseBranch: 'hotfix',
                push: true,
                startOnly: true
            },
            hotfixFinish: {
                commitMessage: 'Hotfix v%VERSION%',
                tempReleaseBranch: 'hotfix',
                push: false,
                finishOnly: true
            }
        }
},
```

_Removing the nested **options** object from hotfixStart, hotfixFinish._

**Comment by passelin** [comment]
I think the issue is that you need to make the sg_release task a multi-task (registerMultiTask instead of registerTask) for it to support targets. Try it out and and let me know; I'll take a closer look tomorrow if it still doesn't work.

I created a [gitter chat room](https://gitter.im/SunGard-Labs/grunt-sg-release?utm_source=share-link&utm_medium=link&utm_campaign=share-link) room for this project.

**Comment by maxfriedmann** [comment]
Of course! How could I not see that, it says that 5 times in the Grunt Docu :)

I was so focused on my nested options... It works now as expected, will do some final cleanup and send you a pull request!
